### PR TITLE
migrate to vite compiler

### PR DESCRIPTION
**Pull request by gqio**

### CODE REVIEW

**Comment by gqio** [comment]
Took me a while about the react version.

**Comment by gqio** [comment]
Before merging this .... we need to migrate yogi to vite

**Review by mveres — APPROVED** [review]
💯

**Comment by gqio** [comment]
Still issues with Firefox we need to fix:
- max recursion error: I really do not have any idea how to solve this (maybe @gluck have an idea)
- we have a dynamic module import for tailwind we need to remove (or use something else)

**Pull request merged**
